/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package pancasila;

import java.awt.CardLayout;
import java.awt.Color;
import java.awt.Dimension;
import java.awt.event.MouseAdapter;
import java.awt.event.MouseEvent;
import java.awt.event.MouseListener;
import javax.swing.Icon;
import javax.swing.ImageIcon;
import javax.swing.JLabel;
import javax.swing.JOptionPane;
/**
 *
 * @author Drinkopi
 */
public class Edutainment extends javax.swing.JFrame {

    /**
     * Creates new form Edutainment
     */
    

    public Edutainment() {
        initComponents();
        
    }

    
    
    
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        Ortu = new javax.swing.JPanel();
        Home = new javax.swing.JPanel();
        btnStart = new javax.swing.JLabel();
        bgHome = new javax.swing.JLabel();
        Welcome = new javax.swing.JPanel();
        btnNext = new javax.swing.JLabel();
        bgWelcome = new javax.swing.JLabel();
        Menu = new javax.swing.JPanel();
        btnGame = new javax.swing.JLabel();
        btnHow = new javax.swing.JLabel();
        btnScore = new javax.swing.JLabel();
        bgMenu = new javax.swing.JLabel();
        HowTo1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        btnHow1 = new javax.swing.JLabel();
        bgHowTo1 = new javax.swing.JLabel();
        HowTo2 = new javax.swing.JPanel();
        btnBack = new javax.swing.JLabel();
        bgHowTo2 = new javax.swing.JLabel();
        Soal1 = new javax.swing.JPanel();
        txtSoal1 = new javax.swing.JLabel();
        pilih1 = new javax.swing.JLabel();
        pilih2 = new javax.swing.JLabel();
        pilih3 = new javax.swing.JLabel();
        pilih4 = new javax.swing.JLabel();
        Soal2 = new javax.swing.JPanel();
        txtSoal2 = new javax.swing.JLabel();
        pilihan1_2 = new javax.swing.JLabel();
        pilihan2_2 = new javax.swing.JLabel();
        pilihan3_2 = new javax.swing.JLabel();
        pilihan4_2 = new javax.swing.JLabel();
        Score = new javax.swing.JPanel();
        ctkPoint = new javax.swing.JLabel();
        bg_Score = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        Ortu.setPreferredSize(new java.awt.Dimension(1366, 768));
        Ortu.setLayout(new java.awt.CardLayout());

        Home.setLayout(null);

        btnStart.setFont(new java.awt.Font("Cooper Black", 1, 48)); // NOI18N
        btnStart.setForeground(new java.awt.Color(255, 128, 73));
        btnStart.setText("START");
        btnStart.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnStart.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnStartMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btnStartMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btnStartMouseExited(evt);
            }
        });
        Home.add(btnStart);
        btnStart.setBounds(280, 490, 190, 60);

        bgHome.setFont(new java.awt.Font("Bookman Old Style", 1, 12)); // NOI18N
        bgHome.setIcon(new javax.swing.ImageIcon(getClass().getResource("/pancasila/img/1.png"))); // NOI18N
        Home.add(bgHome);
        bgHome.setBounds(0, 0, 1370, 768);

        Ortu.add(Home, "Home");

        Welcome.setLayout(null);

        btnNext.setFont(new java.awt.Font("Cooper Black", 1, 48)); // NOI18N
        btnNext.setForeground(new java.awt.Color(255, 128, 73));
        btnNext.setText("NEXT");
        btnNext.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnNext.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnNextMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btnNextMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btnNextMouseExited(evt);
            }
        });
        Welcome.add(btnNext);
        btnNext.setBounds(850, 670, 160, 60);

        bgWelcome.setIcon(new javax.swing.ImageIcon(getClass().getResource("/pancasila/img/2.png"))); // NOI18N
        Welcome.add(bgWelcome);
        bgWelcome.setBounds(0, 0, 1370, 770);

        Ortu.add(Welcome, "Welcome");

        Menu.setLayout(null);

        btnGame.setFont(new java.awt.Font("KaiTi", 1, 36)); // NOI18N
        btnGame.setForeground(new java.awt.Color(255, 255, 255));
        btnGame.setText("START GAME");
        btnGame.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnGameMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btnGameMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btnGameMouseExited(evt);
            }
        });
        Menu.add(btnGame);
        btnGame.setBounds(150, 470, 240, 40);

        btnHow.setFont(new java.awt.Font("KaiTi", 1, 24)); // NOI18N
        btnHow.setForeground(new java.awt.Color(255, 255, 255));
        btnHow.setText("\"How To\"");
        btnHow.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnHow.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnHowMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btnHowMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btnHowMouseExited(evt);
            }
        });
        Menu.add(btnHow);
        btnHow.setBounds(220, 538, 110, 40);

        btnScore.setFont(new java.awt.Font("KaiTi", 1, 36)); // NOI18N
        btnScore.setForeground(new java.awt.Color(255, 255, 255));
        btnScore.setText("Score Board");
        Menu.add(btnScore);
        btnScore.setBounds(160, 612, 230, 50);

        bgMenu.setIcon(new javax.swing.ImageIcon(getClass().getResource("/pancasila/img/3.png"))); // NOI18N
        Menu.add(bgMenu);
        bgMenu.setBounds(0, 0, 1366, 768);

        Ortu.add(Menu, "Menu");

        HowTo1.setLayout(null);
        HowTo1.add(jLabel1);
        jLabel1.setBounds(590, 690, 0, 0);

        btnHow1.setFont(new java.awt.Font("Cooper Black", 1, 48)); // NOI18N
        btnHow1.setForeground(new java.awt.Color(255, 128, 73));
        btnHow1.setText("NEXT");
        btnHow1.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnHow1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnHow1MouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btnHow1MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btnHow1MouseExited(evt);
            }
        });
        HowTo1.add(btnHow1);
        btnHow1.setBounds(370, 650, 160, 60);

        bgHowTo1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/pancasila/img/4.png"))); // NOI18N
        HowTo1.add(bgHowTo1);
        bgHowTo1.setBounds(0, 0, 1366, 770);

        Ortu.add(HowTo1, "HowTo1");

        HowTo2.setLayout(null);

        btnBack.setFont(new java.awt.Font("Cooper Black", 1, 48)); // NOI18N
        btnBack.setForeground(new java.awt.Color(255, 128, 73));
        btnBack.setText("BACK TO MENU");
        btnBack.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnBack.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnBackMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btnBackMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btnBackMouseExited(evt);
            }
        });
        HowTo2.add(btnBack);
        btnBack.setBounds(190, 650, 430, 60);

        bgHowTo2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/pancasila/img/5.png"))); // NOI18N
        HowTo2.add(bgHowTo2);
        bgHowTo2.setBounds(0, 0, 1366, 770);

        Ortu.add(HowTo2, "HowTo2");

        txtSoal1.setText("Apa ibu kota Indonesia?");

        pilih1.setText("Merah");
        pilih1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                pilih1MouseClicked(evt);
            }
        });

        pilih2.setText("Biru");
        pilih2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                pilih2MouseClicked(evt);
            }
        });

        pilih3.setText("jLabel4");

        pilih4.setText("jLabel5");

        javax.swing.GroupLayout Soal1Layout = new javax.swing.GroupLayout(Soal1);
        Soal1.setLayout(Soal1Layout);
        Soal1Layout.setHorizontalGroup(
            Soal1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(Soal1Layout.createSequentialGroup()
                .addGroup(Soal1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(Soal1Layout.createSequentialGroup()
                        .addGap(260, 260, 260)
                        .addComponent(txtSoal1, javax.swing.GroupLayout.PREFERRED_SIZE, 380, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(Soal1Layout.createSequentialGroup()
                        .addGap(161, 161, 161)
                        .addGroup(Soal1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(pilih2, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(pilih1, javax.swing.GroupLayout.PREFERRED_SIZE, 51, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(259, 259, 259)
                        .addGroup(Soal1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(pilih4, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(pilih3, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap(726, Short.MAX_VALUE))
        );
        Soal1Layout.setVerticalGroup(
            Soal1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(Soal1Layout.createSequentialGroup()
                .addGap(270, 270, 270)
                .addComponent(txtSoal1)
                .addGap(65, 65, 65)
                .addGroup(Soal1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(pilih1)
                    .addComponent(pilih3))
                .addGap(49, 49, 49)
                .addGroup(Soal1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(pilih2)
                    .addComponent(pilih4))
                .addContainerGap(336, Short.MAX_VALUE))
        );

        Ortu.add(Soal1, "Soal1");

        txtSoal2.setText("Berapa hasil dari 2 + 2?");

        pilihan1_2.setText("jLabel3");

        pilihan2_2.setText("jLabel4");

        pilihan3_2.setText("jLabel5");

        pilihan4_2.setText("jLabel6");

        javax.swing.GroupLayout Soal2Layout = new javax.swing.GroupLayout(Soal2);
        Soal2.setLayout(Soal2Layout);
        Soal2Layout.setHorizontalGroup(
            Soal2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(Soal2Layout.createSequentialGroup()
                .addGroup(Soal2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(Soal2Layout.createSequentialGroup()
                        .addGap(285, 285, 285)
                        .addGroup(Soal2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(pilihan2_2, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(pilihan1_2, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(198, 198, 198)
                        .addGroup(Soal2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(pilihan3_2, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(pilihan4_2, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(Soal2Layout.createSequentialGroup()
                        .addGap(314, 314, 314)
                        .addComponent(txtSoal2, javax.swing.GroupLayout.PREFERRED_SIZE, 252, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(800, Short.MAX_VALUE))
        );
        Soal2Layout.setVerticalGroup(
            Soal2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(Soal2Layout.createSequentialGroup()
                .addGap(238, 238, 238)
                .addComponent(txtSoal2, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(Soal2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(pilihan1_2)
                    .addComponent(pilihan3_2))
                .addGroup(Soal2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(Soal2Layout.createSequentialGroup()
                        .addGap(62, 62, 62)
                        .addComponent(pilihan2_2))
                    .addGroup(Soal2Layout.createSequentialGroup()
                        .addGap(54, 54, 54)
                        .addComponent(pilihan4_2)))
                .addContainerGap(385, Short.MAX_VALUE))
        );

        Ortu.add(Soal2, "Soal2");

        Score.setLayout(null);

        ctkPoint.setText("jLabel7");
        Score.add(ctkPoint);
        ctkPoint.setBounds(590, 290, 38, 16);

        bg_Score.setIcon(new javax.swing.ImageIcon(getClass().getResource("/pancasila/img/7.png"))); // NOI18N
        Score.add(bg_Score);
        bg_Score.setBounds(0, 0, 1366, 770);

        Ortu.add(Score, "Score");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 1366, Short.MAX_VALUE)
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addGap(0, 0, Short.MAX_VALUE)
                    .addComponent(Ortu, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(0, 0, Short.MAX_VALUE)))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 768, Short.MAX_VALUE)
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addGap(0, 0, Short.MAX_VALUE)
                    .addComponent(Ortu, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(0, 0, Short.MAX_VALUE)))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnStartMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnStartMouseClicked
        //Dapatkan referensi dari CardLayout yang digunakan oleh parent
        CardLayout cardLayout = (CardLayout) Ortu.getLayout();
        //Pindah ke JPanel Welcome
        cardLayout.show(Ortu, "Welcome");
    }//GEN-LAST:event_btnStartMouseClicked

    private void btnStartMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnStartMouseEntered
        btnStart.setForeground(new Color(255,182,0));
    }//GEN-LAST:event_btnStartMouseEntered

    private void btnStartMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnStartMouseExited
        btnStart.setForeground(new Color(255,128,73));
    }//GEN-LAST:event_btnStartMouseExited

    private void btnNextMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnNextMouseClicked
        //Dapatkan referensi dari CardLayout yang digunakan oleh parent
        CardLayout cardLayout = (CardLayout) Ortu.getLayout();
        //Pindah ke JPanel Welcome
        cardLayout.show(Ortu, "Menu");
    }//GEN-LAST:event_btnNextMouseClicked

    private void btnNextMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnNextMouseEntered
        btnNext.setForeground(new Color(255,182,0));
    }//GEN-LAST:event_btnNextMouseEntered

    private void btnNextMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnNextMouseExited
        btnNext.setForeground(new Color(255,128,73));
    }//GEN-LAST:event_btnNextMouseExited

    private void btnHow1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnHow1MouseClicked
        //Dapatkan referensi dari CardLayout yang digunakan oleh parent
        CardLayout cardLayout = (CardLayout) Ortu.getLayout();
        //Pindah ke JPanel Welcome
        cardLayout.show(Ortu, "HowTo2");
    }//GEN-LAST:event_btnHow1MouseClicked

    private void btnHow1MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnHow1MouseEntered
        btnHow1.setForeground(new Color(255,182,0));
    }//GEN-LAST:event_btnHow1MouseEntered

    private void btnHow1MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnHow1MouseExited
        btnHow1.setForeground(new Color(255,128,73));
    }//GEN-LAST:event_btnHow1MouseExited

    private void btnBackMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnBackMouseClicked
        //Dapatkan referensi dari CardLayout yang digunakan oleh parent
        CardLayout cardLayout = (CardLayout) Ortu.getLayout();
        //Pindah ke JPanel Welcome
        cardLayout.show(Ortu, "Menu");
    }//GEN-LAST:event_btnBackMouseClicked

    private void btnBackMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnBackMouseEntered
        btnBack.setForeground(new Color(255,182,0));
    }//GEN-LAST:event_btnBackMouseEntered

    private void btnBackMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnBackMouseExited
        btnBack.setForeground(new Color(255,128,73));
    }//GEN-LAST:event_btnBackMouseExited

    private void btnHowMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnHowMouseClicked
        //Dapatkan referensi dari CardLayout yang digunakan oleh parent
        CardLayout cardLayout = (CardLayout) Ortu.getLayout();
        //Pindah ke JPanel Welcome
        cardLayout.show(Ortu, "HowTo1");
    }//GEN-LAST:event_btnHowMouseClicked

    private void btnHowMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnHowMouseEntered
        btnHow.setForeground(new Color(50,50,50));
    }//GEN-LAST:event_btnHowMouseEntered

    private void btnHowMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnHowMouseExited
        btnHow.setForeground(new Color(255,255,255));
    }//GEN-LAST:event_btnHowMouseExited

    private void btnGameMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnGameMouseClicked
        //Dapatkan referensi dari CardLayout yang digunakan oleh parent
        CardLayout cardLayout = (CardLayout) Ortu.getLayout();
        //Pindah ke JPanel Welcome
        cardLayout.show(Ortu, "Soal1");
    }//GEN-LAST:event_btnGameMouseClicked

    private void btnGameMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnGameMouseEntered
        btnGame.setForeground(new Color(50,50,50));
    }//GEN-LAST:event_btnGameMouseEntered

    private void btnGameMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnGameMouseExited
        btnGame.setForeground(new Color(255,255,255));
    }//GEN-LAST:event_btnGameMouseExited

    private void pilih1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_pilih1MouseClicked
        // Cek jawaban yang benar (Anda dapat menyesuaikan jawaban sesuai kebutuhan)
        if (pilih1.getText().equals("Merah")) {
            JOptionPane.showMessageDialog(null, "Jawaban salah. Coba lagi!");
        }
    }//GEN-LAST:event_pilih1MouseClicked

    private void pilih2MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_pilih2MouseClicked
        // Cek jawaban yang benar (Anda dapat menyesuaikan jawaban sesuai kebutuhan)
        if (pilih2.getText().equals("Biru")) {
            //Dapatkan referensi dari CardLayout yang digunakan oleh parent
            CardLayout cardLayout = (CardLayout) Ortu.getLayout();
            //Pindah ke JPanel Welcome
            cardLayout.show(Ortu, "Soal2");
            JOptionPane.showMessageDialog(null, "Jawaban Benar. Semangat!");
        }
    }//GEN-LAST:event_pilih2MouseClicked

    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Edutainment.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Edutainment.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Edutainment.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Edutainment.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Edutainment().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel Home;
    private javax.swing.JPanel HowTo1;
    private javax.swing.JPanel HowTo2;
    private javax.swing.JPanel Menu;
    private javax.swing.JPanel Ortu;
    private javax.swing.JPanel Score;
    private javax.swing.JPanel Soal1;
    private javax.swing.JPanel Soal2;
    private javax.swing.JPanel Welcome;
    private javax.swing.JLabel bgHome;
    private javax.swing.JLabel bgHowTo1;
    private javax.swing.JLabel bgHowTo2;
    private javax.swing.JLabel bgMenu;
    private javax.swing.JLabel bgWelcome;
    private javax.swing.JLabel bg_Score;
    private javax.swing.JLabel btnBack;
    private javax.swing.JLabel btnGame;
    private javax.swing.JLabel btnHow;
    private javax.swing.JLabel btnHow1;
    private javax.swing.JLabel btnNext;
    private javax.swing.JLabel btnScore;
    private javax.swing.JLabel btnStart;
    private javax.swing.JLabel ctkPoint;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel pilih1;
    private javax.swing.JLabel pilih2;
    private javax.swing.JLabel pilih3;
    private javax.swing.JLabel pilih4;
    private javax.swing.JLabel pilihan1_2;
    private javax.swing.JLabel pilihan2_2;
    private javax.swing.JLabel pilihan3_2;
    private javax.swing.JLabel pilihan4_2;
    private javax.swing.JLabel txtSoal1;
    private javax.swing.JLabel txtSoal2;
    // End of variables declaration//GEN-END:variables
}
